# Generated by Django 3.0 on 2023-08-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
